// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using October21stEFCoreCodeFirst.DataLayer.Context;

namespace October22ndEFCoreCodeFirst.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20201022233552_InitalCreate")]
    partial class InitalCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0-rc.2.20475.6");

            modelBuilder.Entity("October22ndEFCoreCodeFirst.DataLayer.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Prodcuts");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Category = "Sports",
                            Name = "Basketball"
                        },
                        new
                        {
                            ID = 2,
                            Category = "Sports",
                            Name = "Baseball Bat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
